spring:
  datasource:
    username: root
    password: Wtm0gp1pjw
    url: jdbc:mysql://localhost:3306/blogPost?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

security:
  corsAllowedOrigins: "http://localhost:1234"
  corsAllowedMethods: "GET,POST,PUT,PATCH,DELETE"
  permitUrls: "/login, /register"
